#!/bin/bash
gdbus monitor -y -d org.freedesktop.login1 | awk '
/LockedHint/ && /<true>/ { print "sleep 15; lampster off\n"; fflush(STDOUT); }
/LockedHint/ && /<false>/ { print "lampster on\n"; fflush(STDOUT); }
'  | bash #-v

